linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 120
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - typeDefFirst
      - hugeParam
      - rangeValCopy
      - exitAfterDefer
      - whyNoLint
      - singleCaseSwitch
      - commentedOutCode

linters:
  disable-all: true
  enable:
    - dogsled
    - errcheck
    - goconst
    - gocritic # go1.18
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace

  # Do not enable:
  # - wsl       (too opinionated about newlines)
  # - godox     (todos are OK)
  # - bodyclose (false positives on helper functions)
  # - prealloc  (not worth it in scope of this project)
  # - maligned  (same as prealloc)
  # - funlen    (gocyclo is enough)

issues:
  exclude-use-default: false
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
    - path: _test\.go
      linters:
        - revive
      text: unused-parameter

    # Allow unused context.Context
    - linters:
        - revive
      text: unused-parameter
      source: .+\s+context.Context

    # Allow embed globals
    - source: "embed\\.FS"
      linters: [gochecknoglobals]

    # Exclude go:generate from lll
    - source: "//go:generate"
      linters: [lll]

    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - scopelint
        - lll
        - gochecknoglobals
    # Ignore shadowing of err.
    - linters: [govet]
      text: 'declaration of "(err|ctx|log)"'

    # Ignore linters in main packages.
    - path: cmd/.+\.go
      linters: [goconst, funlen, gocognit, gocyclo]

    - linters: [gosec]
      text: (G304|G204)

    - linters: [revive]
      text: "comment on exported const .+ should be of the form"
    - linters: [revive]
      text: "exported const .+ should have comment"

    # Not gonna use const, does not make any sense.
    - linters: [goconst]
      text: "(Int64|int)"
    - path: "internal/logparser"
      linters: [goconst]
      text: "(trace|span)_?[Ii][Dd]"
